name: Publish release image

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - id: version
        shell: bash
        run: echo "release-version=$(echo ${GITHUB_REF:10})" >> $GITHUB_OUTPUT

      - name: Publish to GitHub Container Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          tags: "${{ steps.version.outputs.release-version }}"
